services:
  database:
    container_name: agents-db
    image: pgvector/pgvector:pg18
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Use the prisma migrations to provide extensions
      # - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - pg-data:/var/lib/postgresql

volumes:
  pg-data:
